### ISSUE TITLE
Bug: html lang tag

### ISSUE THREAD

**Issue by EarthlingDavey** [fand/MDMT#5]
It looks like this is set to en at all times. 

I have tried to find a solution but unfortunately it seems like a very difficult thing to do with nextjs.

**Comment by fand** [comment]
Just fixed it [here]( https://github.com/fand/MDMT/commit/07e79bf5806386f94b3dba72e9abd8e1dd4a4f00#diff-8f3a5cf5019173ef1f56a54e45e44747R58 ). Thanks!
